[project]
name = "payments-backend"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.111",
  "uvicorn[standard]>=0.30",
  "pydantic>=2.7",
  "python-dotenv>=1.0",
]

[tool.flake8]
max-line-length = 100
ignore = ["E203", "W503"]
